let fullbody = document.querySelector(".fullbody");
let header = document.querySelector(".header");
let heading = document.querySelector(".heading");
let emoji = document.querySelector(".emoji");
let memeText = document.querySelector(".meme");
let btnMeme = document.querySelector(".memeBtn");

let listMeme = [
  "I have purchased a purse to keep my money but all  money spend to buy the purse and the purse is blank now.... ",
  "I'm reading a book on anti-gravity. It's impossible to put down...",
  "Why don't scientists trust atoms? Beacause they make up everything......",
  "Why don't eggs tell jokes ? They'd crack each other up...",
  "why did the tomato turn red ? Because it saw the salad dressing...",
  "What do you call a fake noodle ? An impasta...",
  "Why did the coffee file a police report ? It got mugged...",
  "Why did the bicycle fall over ? Because it was two-tired ...",
  "What do you call a can opener that doesn't work ? A can't operner...",
  "Why did the banana go to the doctor ? He wasn't peeling well...",
  "Why did the astronat break up with his girlfriend ? He needed space...",
  "Why did computer go to doctor ? Because it has virus...",
  "Why did the egg go to therapy ? It was cracking under the pressure...",
  "What's the best thing about Switzerland? The flag is a big plus....",
  "I went to the aquarium this weekend, but I didn’t stay long. There’s something fishy about that place....",
  "I found a lion in my closet the other day! When I asked what it was doing there, it said “Narnia business.”...",
  "What's a cat's favorite instrument? Purr-cussion....",
  "Why did the snail paint a giant S on his car? So when he drove by, people could say: “Look at that S car go!”...",
  "What do you call a happy cowboy? A jolly rancher....",
  "What subject do cats like best in school? Hiss-tory....",
  "Humpty Dumpty had a great fall. He said his summer was pretty good too....",
  "My boss said “dress for the job you want, not for the job you have.” So I went in as Batman....",
  "How do you make holy water? You boil the hell out of it....",
  "Justice is a dish best served cold. Otherwise, it's just water....",
  "Why should you never throw grandpa's false teeth at a vehicle? You might denture car....",
  "Why are Christmas trees bad at knitting? They always drop their needles....",
  "What did the lunch box say to the refrigerator? Don't hate me because I'm a little cooler....",
  "I can always tell when someone is lying. I can tell when they're standing too....",
  "Some people pick their nose, but I was born with mine....",
  "What's the coolest element in the periodic table? Ber-yllium...",
  "I used to be afraid of speed bumps. I'm trying to get over it....",
  "If your house is cold, just stand in the corner. It’s always 90 degrees there....",
  "I don't recommend entering a wormhole. You might get stuck in the apple....",
  "The owner of the tuxedo store kept hovering over me when i was browsing, so I asked him to leave me alone. He said, “Fine, suit yourself.”...",
  "Why did the egg have a day off? Because it was Fryday....",
  "Have you ever heard about the kidnapping at school? It's okay, he woke up....",
  "I found a book called How to Solve 50% of Your Problems. So I bought 2....",
  "What do Keanu Reeves and baby Yoda have in common? They age at the same rate....",
  "Why did the coffee taste like dirt? Because it was ground just a few minutes ago....",
  "Why can't you make a dinosaur omelet? Because they're egg-stinct....",
  "Why do quarterbacks tell obvious jokes? So they don't go over their receivers' heads....",
  "Why did the Rolling Stones stop making music? Because they got to bottom of the hill....",
  "How many goats does it take to change a lightbulb? Just one, but you have to goat them into it....",
  "What did one cupcake say to the other? You ain't see muffin yet....",
  "What is the best present? Broken drums! You can't beat them....",
  "Did you hear about the new squirrel diet? It's just nuts....",
  "I made song about tortilla once, now it's more like a wrap....",
  "Did you hear about the spatula's hot new flame? It met the grill of its dreams....",
  "Did you know corduroy pillows are in style? They're making headlines....",
  "What does a nosey pepper do? It gets jalapeño business....",
  "Did you hear about the fragile myth? It was busted....",
  "Did you hear about the pirate who became a great chef? He mastered the seven sea-sonings....",
  "What word can you make shorter by adding two letters? Short....",
  "When does a hippo have a tusk? After some rhino-plasty....",
  "What do call a criminal landing an airplane? Condescending....",
  "I decided to sell my vacuum cleaner. It was just gathering dust....",
  "I stayed up all night wondering where the sun went, and then it dawned on me....",
  "Why do people who live in Greece hate waking up at dawn? Because Dawn is tough on Greece....",
  "I ordered a chicken and an egg from Amazon. I'll let you know....",
  "What month is the shortest of the year? May, it only has three letters....",
  "What did the snail who was riding on the turtle's back say? Wheeeee!...",
  "I was going to tell a time traveling joke, but you guys didn't like it....",
  "What do you call a lazy kangaroo? A pouch potato....",
  "I used to run a dating service for chickens, but I was struggling to make hens meet....",
  "Why do we tell actors to 'break a leg?' Because every play has a cast....",
  "What does a pig put on dry skin? Oinkment....",
  "What do you call it when a snowman throws a tantrum? A meltdown....",
  "My uncle named his dogs Timex and Rolex. They're his watch dogs....",
  "Did you hear about the guy whose left side was cut off? He's all right now....",
  "How do you open a banana? With a mon-key....",
  "Which is faster, hot or cold? Hot, because you can catch cold....",
  "What did one plate say to the other plate? Dinner's on me....",
  "Why do oranges wear sunscreen? So they don't peel....",
  "My wife told me to stop acting like a flamingo, so I had to put my foot down....",
  "What do you call a pig that does karate? A pork chop....",
  "Where does Batman go to the bathroom? The batroom....",
  "What do you call a pony with a sore throat? A little horse....",
  "What did the left eye say to the right eye? Between you and me, something smells....",
  "What did the mama tomato say to the baby tomato? Catch up!...",
  "Why didn't the melons get married? Because they cantaloupe....",
  "What do you call a fake noodle? An impasta....",
  "How did the pig get to the hogspital? In a hambulance....",
  "I'm so good at sleeping I can do it with my eyes closed!...",
  "Why does Humpty Dumpty love autumn? Because he had a great fall....",
  "What happens when a strawberry gets run over crossing the street? Traffic jam....",
  "Why did the cow jump over the moon? The farmer had cold hands....",
  "A termite walks into a bar and says, 'So, is the bar tender here?...",
  "How does an octopus go into battle? Well-armed....",
  "What do you call a pudgy psychic? A four-chin teller....",
];

btnMeme.addEventListener("click", (e) => {
  btnMeme.innerHTML = "Change Jokes"
  let randomNum = Math.floor(Math.random() * 87);
  let randomMeme = listMeme[randomNum];
  e.target.previousElementSibling.innerHTML = randomMeme;
});
